---
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "install process started"
      - npm install
  build:
    commands:
      - echo "build process started"
      - npm ci
      - npm install -g serverless@3.40.0
  post_build:
    commands:
      - echo "build process finished, Updating lambda Function..."
      - echo "Updating lambda Function..."
      - echo "Deploying with stage:$stage"
      - sls deploy --stage $stage
      - echo "Deployment is DONE!!"
artifacts:
  files:
    - "**/*"
    - dist/**/*
    - node_modules/**/*
    - package.json
    - package-lock.json

